language: go

go:
  - 1.7
  - tip

branches:
  only:
  - master
  - dev

env:
  - key=q56mdvdzreye
  - secret=spmf6x2b2v2tqg93sfp5t393wfcxru58zm7jr3ynf7dmmndw5y8chux25hs63znf
  - region=us-east
  - app_id=16013